### ISSUE TITLE
More instances

### ISSUE THREAD

**Issue by fizruk** [fizruk/http-api-data#10]
How about instances for these guys from `base`:
- `Char`;
- `Data.Monoid` newtypes;
- [`Version`](http://hackage.haskell.org/package/base/docs/Data-Version.html);
- `[a]` and `ZipList a`;
- tuples (up to some reasonable number);
- `Void`.

**Comment by gregwebs** [comment]
It is difficult to define a universal [a]. Better to avoid that for now and use newtypes

**Comment by jkarni** [comment]
What would be the instance for `Void`? I don't really understand why `Void` even has a `Read` instance...

**Comment by fizruk** [comment]
@jkarni the instances should look like this:

```haskell
instance ToHttpApiData Void where
  toUrlPiece = absurd

instance FromHttpApiData Void where
  fromUrlPiece = Left "Void cannot be parsed!"
```

`Read` and `FromHttpApiData` instances might be useful for structures like, e.g. `Free f Void` which might have perfectly valid values (`Void` only makes some parts of that structure impossible to construct).

**Comment by jkarni** [comment]
That makes sense!
