### ISSUE TITLE
Generic deriving

### ISSUE THREAD

**Issue by fizruk** [fizruk/http-api-data#12]
I've been thinking about Generic deriving (suggested in https://github.com/fizruk/http-api-data/issues/3#issuecomment-145364692) and it probably will not work. Consider this example:

```haskell
data Example = Example Text Text
```

`Text` is always encoded as is, so there is no safe way to encode `Example`.

So it might only make sense to derive instances for constructors with at most one field, e.g.:

```haskell
data Account = User Text | Org Text
data Action = Create | Read | Update | Delete deriving (Show)
```

We could provide TH code to generate instances for those, but I don't think it is worth adding anymore.
Besides there's almost no boilerplate for enumerations:

```haskell
instance ToHttpApiData Action where
  toUrlPiece = showUrlPiece

instance FromHttpApiData Action where
  parseUrlPiece = readEitherUrlPiece
```

Thoughts?

**Comment by gregwebs** [comment]
I prefer to have a simple statement that Show, Read, etc is being used than to have Generic/TH deriving.

**Comment by fizruk** [comment]
Agreed, no Generic/TH deriving is necessary.
