### ISSUE TITLE
Allow base-4.20

### ISSUE THREAD

**Issue by andreasabel** [fizruk/http-api-data#139]
> [__3] rejecting: base-4.20.0.0/installed-8a80 (conflict: http-api-data => base>=4.10.1.0 && <4.20)

**Comment by phadej** [comment]
Blocked on https://github.com/haskell-unordered-containers/unordered-containers/issues/489 and softly blocked on https://github.com/haskell/entropy/issues/84

**Comment by phadej** [comment]
Update: `entropy` is kind-of blocked on https://github.com/haskell/cabal/issues/10010 too. I don't like idea of installing older `Cabal`s for its `build-type: Custom`.

So currently I'll wait until there is `cabal-install` release.
