### ISSUE TITLE
Export helpers

### ISSUE THREAD

**Issue by fizruk** [fizruk/http-api-data#18]
As @gregwebs pointed out in [his comment](https://github.com/yesodweb/persistent/pull/490/files#r41693286) for yesodweb/persistent#490, libraries that depend on `http-api-data` should not use `.Internal` module.

So far the following functions from `Web.HttpApiData.Internal` seem to be useful in other libraries (for `servant-server` and `persistent`):
- `parseUrlPieceMaybe` ([use case](https://github.com/haskell-servant/servant/blob/3ce7c9758ac1f35896aa3559281dd7bb2ae1d400/servant-server/src/Servant/Server/Internal.hs#L95));
- `parseHeaderMaybe` ([use case](https://github.com/haskell-servant/servant/blob/3ce7c9758ac1f35896aa3559281dd7bb2ae1d400/servant-server/src/Servant/Server/Internal.hs#L308));
- `parseQueryParamMaybe` ([use case](https://github.com/haskell-servant/servant/blob/3ce7c9758ac1f35896aa3559281dd7bb2ae1d400/servant-server/src/Servant/Server/Internal.hs#L479));
- `parseUrlPieceWithPrefix` ([use case](https://github.com/yesodweb/persistent/pull/490/files#diff-3a25833edb66bce17829c31eec6c4e69R222));
- `showTextData` ([use case](https://github.com/yesodweb/persistent/pull/490/files#diff-e5ccaeacc246e59ac9c0ad99f9a2be55R89));
- `readEitherTextData` ([use case](https://github.com/yesodweb/persistent/pull/490/files#diff-3a25833edb66bce17829c31eec6c4e69R223));
- `parseBoundedCaseInsensitiveTextData` ([use case](https://github.com/yesodweb/persistent/pull/490/files#diff-e5ccaeacc246e59ac9c0ad99f9a2be55R92)).

@gregwebs suggested to use `Web.HttpApiData.Utils` or `Web.HttpApiData.Parse` for these. The latter is not suitable for `showTextData` though.

OTOH current naming should not overlap with other libraries and we might as well export those from `Web.HttpApiData` directly.

Thoughts?

**Comment by gregwebs** [comment]
yeah, exporting them all from Web.HttpApiData is probably best
