### ISSUE TITLE
Check integral value bounds

### ISSUE THREAD

**Issue by fizruk** [fizruk/http-api-data#2]
Neither `read` nor `Data.Text.Read` readers check integer bounds. E.g.:

```
>>> maxBound :: Int8
127
>>> read "128" :: Int8
-128
>>> fst <$> decimal "128" :: Either String Int8
Right (-128)
```

`path-pieces` package had `parseIntegral` helper which parsed `Integer` and then checked if bounds are violated. Instances in `Servant.Common.Text` do not have this.

Should we perform this check?

**Comment by gregwebs** [comment]
It seems like a good idea to always use whichever parser is the most stringent

**Comment by fizruk** [comment]
On the other hand wouldn't bounds checking affect performance?
Which of safety/performance should be preferred here?
I do not have a strong opinion.

**Comment by gregwebs** [comment]
I am very much on the side of safety and correctness first, then benchmarking, then optimizing.
