### ISSUE TITLE
UUID instances?

### ISSUE THREAD

**Issue by fizruk** [fizruk/http-api-data#21]
This is straightforward to do and [`uuid`](https://hackage.haskell.org/package/uuid) is likely to be among other dependencies (at least I think so).

@gregwebs what do you think?

**Comment by gregwebs** [comment]
The preferred way would be for uuid to depend on http-api-data or perhaps to have a http-api-data-instances package. It is definitely not a safe assumption that uuid will be a dependency. Some projects use it and some don't. Personally I think [cuid](https://hackage.haskell.org/package/hscuid) is often more appropriate than uuid (v4).
