### ISSUE TITLE
Bring To/FromFormUrlEncoded from servant

### ISSUE THREAD

**Issue by fizruk** [fizruk/http-api-data#23]
Probably with a generic deriving mechanism for records, whose fields have `To/FromHttpApiData` instances.

**Comment by jkarni** [comment]
I'll work on this.

**Comment by jkarni** [comment]
Any thoughts about what do with the generic instance for non-record datatypes? One option is to expect the keys to be integers, as a positional specification of the values. The other is to not have an instance for it, so that they have to be declared manually.

**Comment by jkarni** [comment]
I myself am inclined to only allow record fields. It'd be too confusing to write the corresponding HTML otherwise.

**Comment by fizruk** [comment]
We should start with what definitely makes sense — records.
If there will be a need for generic deriving for other data types, we can add those later.
