### ISSUE TITLE
() and Maybe PathPiece instances

### ISSUE THREAD

**Issue by fizruk** [fizruk/http-api-data#3]
[Latest version of `path-piece` on Hackage](http://hackage.haskell.org/package/path-pieces-0.2.0/docs/Web-PathPieces.html) has `PathPiece` instance for `Maybe a` (which is similar to derived `Show` instance for `Maybe`).

[Latest code in `path-piece` repo](https://github.com/yesodweb/path-pieces/tree/f2fc3a6e4d491042c103cf56b12d80ad19565790) also has `PathPiece` instance for `()`:

```haskell
instance PathPiece () where
    fromPathPiece t = if t == "_" then Just () else Nothing
    toPathPiece () = "_"
```

Do these instances make sense? Should we provide a Generic mechanism to derive `To/FromHttpApiData` similar to `Read`/`Show` deriving (i.e. why `Maybe` should be special)?

Or should we just leave them for `PathPiece` class only "for compatibility"?

**Comment by gregwebs** [comment]
[pull request adding unit](https://github.com/yesodweb/path-pieces/pull/9)
[PR for Maybe](https://github.com/yesodweb/path-pieces/pull/7)

**Comment by fizruk** [comment]
Okay, I guess they do make sense.

In this case I suggest the following:
- add `To/FromHttpApiData` instances for `()` with `"_"` representation;
- add Generic-based deriving mechanism for `To/FromHttpApiData` similar to how `Show`/`Read` instances are derived;
- add default signature for `To/FromHttpApiData` classes to use generic implementation;
- add derived instances for as many types in base as it might make sense:
    - `Bool`;
    - `Ordering`;
    - `Maybe a`;
    - `Either a b`;
    - `Complex a`;
    - `Ratio a`;
    - anything else?

I see generic deriving particularly useful for enumerations.
