### ISSUE TITLE
export abstract data type `Form` from Web.FormUrlEncoded module

### ISSUE THREAD

**Issue by cdepillabout** [fizruk/http-api-data#36]
It would be nice if the `Form` data type is exported from the [`Web.FormUrlEncoded`](https://github.com/fizruk/http-api-data/blob/master/src/Web/FormUrlEncoded.hs) module.  There are a couple functions returning a `Form` ([`toForm`](https://hackage.haskell.org/package/http-api-data-0.3.1/docs/Web-FormUrlEncoded.html#v:toForm), [`fromEntriesByKey`](https://hackage.haskell.org/package/http-api-data-0.3.1/docs/Web-FormUrlEncoded.html#v:fromEntriesByKey)), but there is no way to write the type of them in your own code without importing `Form` from `Web.Internal.FormUrlEncoded`.

The constructor of `Form` should probably not be exported.

**Comment by fizruk** [comment]
Yeah, that was probably not intended. Can you make a quick PR (with or without exporting constructor)?
