### ISSUE TITLE
Fix docs for defining instances 

### ISSUE THREAD

**Issue by 3noch** [fizruk/http-api-data#39]
This example from the docs is off:

```
data Person = Person
  { name :: String
  , age  :: Int }

instance FromForm Person where
  fromForm (Form m) = Person
    <$> parseUnique "name" m
    <*> parseUnique "age"  m
```

`Form m` should just be `m`.

**Comment by fizruk** [comment]
Thanks! I wish I could make those code samples to be compiled (like with `doctest`) while keeping it looking nice (e.g. compared to `doctest`'s multiline input). Do you know of a way?

**Comment by fizruk** [comment]
I've finally got to it! Sorry it took so long.

**Comment by 3noch** [comment]
No problem. I have yet to think of a way to do this automatically without messing with appearance...
