### ISSUE TITLE
Add instances for `SetCookie`

### ISSUE THREAD

**Issue by phadej** [fizruk/http-api-data#59]
Would need to add dependencies to http://hackage.haskell.org/package/cookie

Motivation: http://hackage.haskell.org/package/servant-auth-server-0.3.0.0 has http://hackage.haskell.org/package/servant-auth-server-0.3.0.0/src/src/Servant/Auth/Server/SetCookieOrphan.hs module, let's have less orphans.

**Comment by fizruk** [comment]
I see no objections! Let's have someone implement this :)

**Comment by Woody88** [comment]
Hi guys,

I'm looking to contribute to a Haskell project, and since I am using this package in one of my projects I decided to have a look at it. Are there any specifics that I should be aware of before diving in? 

Thanks.

**Comment by phadej** [comment]
@Woody88 not really, please make a PR, I'll be happy to review (and merge after!)

**Comment by phadej** [comment]
Thanks @Woody88 and @fizruk
