### ISSUE TITLE
Use text-show?

### ISSUE THREAD

**Issue by jkarni** [fizruk/http-api-data#6]
Both `path-pieces` and servant's `ToText` frequently have instances that go via `String` (`Show`  instances). We could avoid that altogether by using the `text-show` package, which should be more efficient.

**Comment by gregwebs** [comment]
I hesitate because text-show is not a tiny package and I am not sure how common of a dependency it is. The dependencies for path-pieces are just `text` and `time` right now.

**Comment by fizruk** [comment]
@gregwebs maybe we should add a Cabal flag for this?

**Comment by gregwebs** [comment]
@snoyberg how do you feel about the text-show dependency?

**Comment by gregwebs** [comment]
A cabal flag makes sense to me with the default of not using text-show. Maybe we will become comfortable with the dependency and remove the flag eventually.

**Comment by snoyberg** [comment]
I agree with holding off for now, it's a relatively heavy-weight dependency.
