### ISSUE TITLE
Allow base-4.13.0.0

### ISSUE THREAD

**Issue by nbouscal** [fizruk/http-api-data#93]
To support GHC 8.8.1

**Comment by phadej** [comment]
Blocked on `attoparsec`.

**Comment by nbouscal** [comment]
It looks like `attoparsec` is ready but just needs a new release? Or am I missing something?

(Thanks for the quick reply!!)

**Comment by phadej** [comment]
@nbouscal yes. But I'm pedantic, i.e. I want to see CI pass before making a release / revision.

**Comment by nbouscal** [comment]
Ok, thanks :) I'm working through building things with `allow-newer`, wasn't sure whether it's helpful or not to create issues. (So far the only build failures I'm getting for our applications are `socks` and `memory`, both of which are resolved by merging the open PRs on those repos.)

**Comment by phadej** [comment]
Revision made
